"""Lifecycle policy generated by scripts/s3_archive_and_clean.sh.

The bucket ran with versioning enabled and no lifecycle configuration, which
let ~6.6 TB of noncurrent versions accumulate behind ~47 GB of visible objects.
Expiring versions once does not prevent recurrence — the NoncurrentVersionExpiration
rule does. These tests pin that the rule is emitted, that it does not require
opting into a Glacier transition, and that Glacier does not displace it.

--print-lifecycle exits before any AWS call, so these run offline.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "s3_archive_and_clean.sh"

PROTECT_RULE_ID = "expire-noncurrent-versions"
GLACIER_RULE_ID = "greenfield-archive-to-glacier"


def run_script(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["bash", str(SCRIPT), *args],
        capture_output=True,
        text=True,
        timeout=30,
    )


def lifecycle(*args: str) -> dict:
    proc = run_script("--print-lifecycle", *args)
    assert proc.returncode == 0, f"exit={proc.returncode} stderr={proc.stderr}"
    return json.loads(proc.stdout)


def rules_by_id(cfg: dict) -> dict:
    return {rule["ID"]: rule for rule in cfg["Rules"]}


@unittest.skipIf(shutil.which("bash") is None, "bash unavailable")
class TestLifecyclePolicy(unittest.TestCase):
    def test_script_exists_and_parses(self) -> None:
        self.assertTrue(SCRIPT.is_file())
        proc = subprocess.run(
            ["bash", "-n", str(SCRIPT)], capture_output=True, text=True, timeout=30
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_noncurrent_expiry_does_not_require_glacier(self) -> None:
        """--apply-lifecycle must be usable without archiving anything."""
        rules = rules_by_id(lifecycle())
        self.assertIn(PROTECT_RULE_ID, rules)
        self.assertNotIn(GLACIER_RULE_ID, rules)

        protect = rules[PROTECT_RULE_ID]
        self.assertEqual(protect["Status"], "Enabled")
        self.assertEqual(protect["NoncurrentVersionExpiration"]["NoncurrentDays"], 14)
        self.assertNotIn("Transitions", protect)

    def test_rule_applies_to_whole_bucket(self) -> None:
        protect = rules_by_id(lifecycle())[PROTECT_RULE_ID]
        self.assertEqual(protect["Filter"]["Prefix"], "")

    def test_incomplete_multipart_uploads_are_aborted(self) -> None:
        protect = rules_by_id(lifecycle())[PROTECT_RULE_ID]
        self.assertEqual(
            protect["AbortIncompleteMultipartUpload"]["DaysAfterInitiation"], 7
        )

    def test_glacier_does_not_displace_the_expiry_rule(self) -> None:
        """put-bucket-lifecycle-configuration replaces the whole document, so
        the Glacier variant must carry the protection rule with it."""
        rules = rules_by_id(lifecycle("--glacier"))
        self.assertIn(PROTECT_RULE_ID, rules)
        self.assertIn(GLACIER_RULE_ID, rules)
        self.assertEqual(
            rules[PROTECT_RULE_ID]["NoncurrentVersionExpiration"]["NoncurrentDays"], 14
        )
        self.assertEqual(
            rules[GLACIER_RULE_ID]["Transitions"],
            [{"Days": 0, "StorageClass": "GLACIER"}],
        )

    def test_noncurrent_days_is_configurable(self) -> None:
        rules = rules_by_id(lifecycle("--noncurrent-days", "30"))
        self.assertEqual(
            rules[PROTECT_RULE_ID]["NoncurrentVersionExpiration"]["NoncurrentDays"], 30
        )

    def test_invalid_noncurrent_days_fails_loudly(self) -> None:
        for bad in ("abc", "0", "-1", "7.5", ""):
            with self.subTest(value=bad):
                proc = run_script("--print-lifecycle", "--noncurrent-days", bad)
                self.assertEqual(proc.returncode, 2, f"accepted {bad!r}")
                self.assertIn("positive integer", proc.stderr)

    def test_print_lifecycle_makes_no_aws_calls(self) -> None:
        """Must short-circuit before the credential pre-flight, otherwise the
        policy cannot be reviewed or tested without bucket access."""
        proc = subprocess.run(
            ["bash", str(SCRIPT), "--print-lifecycle"],
            capture_output=True,
            text=True,
            timeout=30,
            env={"PATH": "/usr/bin:/bin", "HOME": "/nonexistent"},
        )
        self.assertEqual(proc.returncode, 0, proc.stderr)
        self.assertIn(PROTECT_RULE_ID, proc.stdout)

    def test_help_documents_the_recurrence_fix(self) -> None:
        proc = run_script("--help")
        self.assertIn("--apply-lifecycle", proc.stdout)
        self.assertIn("--noncurrent-days", proc.stdout)

    def test_default_matches_terraform(self) -> None:
        """Both write rule ID 'expire-noncurrent-versions' and a lifecycle PUT
        replaces the whole document, so divergent retention would flap."""
        tf = (Path(__file__).resolve().parents[1] / "infra" / "main.tf").read_text()
        match = re.search(r"noncurrent_days\s*=\s*(\d+)", tf)
        self.assertIsNotNone(match, "noncurrent_days not found in infra/main.tf")
        self.assertIn(PROTECT_RULE_ID, tf)

        tf_days = int(match.group(1))
        script_days = rules_by_id(lifecycle())[PROTECT_RULE_ID][
            "NoncurrentVersionExpiration"
        ]["NoncurrentDays"]
        self.assertEqual(
            script_days,
            tf_days,
            "s3_archive_and_clean.sh and infra/main.tf disagree on retention",
        )


if __name__ == "__main__":
    unittest.main()
