package com.trading.bookmap;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.InputStream;
import java.util.Properties;

/**
 * Strongly-typed view over {@code build-info.properties}, which is
 * generated by the Gradle {@code writeBuildInfo} task on every build.
 *
 * <p>The file lives at the root of the fat-jar; if it is missing the
 * loader returns sentinel values so the add-on still runs.
 */
public final class BuildInfo {

    private static final Logger LOG = LoggerFactory.getLogger(BuildInfo.class);
    private static final String RESOURCE = "/build-info.properties";

    public final String version;
    public final String buildNumber;
    public final String buildTime;

    private BuildInfo(String version, String buildNumber, String buildTime) {
        this.version = version;
        this.buildNumber = buildNumber;
        this.buildTime = buildTime;
    }

    public static BuildInfo load() {
        Properties p = new Properties();
        try (InputStream in = BuildInfo.class.getResourceAsStream(RESOURCE)) {
            if (in != null) {
                p.load(in);
            }
        } catch (Exception ex) {
            LOG.debug("BuildInfo: failed to read {}", RESOURCE, ex);
        }
        return new BuildInfo(
            p.getProperty("version", "unknown"),
            p.getProperty("buildNumber", "?"),
            p.getProperty("buildTime", "unknown")
        );
    }

    public String shortLabel() {
        return "v" + version + " (build #" + buildNumber + ")";
    }
}
